# Generated by Django 3.2 on 2022-11-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_cantactlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CantactList',
            new_name='ContactList',
        ),
    ]
