# Generated by Django 3.2 on 2022-11-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_token',
            field=models.CharField(default='no token', max_length=100),
        ),
    ]
