# Generated by Django 3.2 on 2022-11-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20221117_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_detail', models.TextField()),
                ('contactlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.contactlist')),
            ],
        ),
    ]
