# Generated by Django 3.2 on 2022-11-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
