# Generated by Django 3.2 on 2022-11-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='relatedFile',
            field=models.ImageField(blank=True, null=True, upload_to='relatedFile'),
        ),
    ]
