# Generated by Django 3.2 on 2022-11-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_product_relatedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
